"""
========================================
College Canteen Food Ordering System
DBMS Mini Project - Sample SQL Queries
========================================

This file contains sample SQL queries that demonstrate DBMS concepts.
These are the SQL equivalents of the ORM operations in the application.

USE THIS FILE FOR:
1. Understanding how ORM translates to SQL
2. DBMS viva preparation
3. Direct database queries if needed
"""

# ========================================
# TABLE CREATION (DDL - Data Definition Language)
# ========================================
# Note: These are auto-generated by SQLAlchemy ORM

CREATE_TABLES_SQL = """
-- ========================================
-- 1. HOSTELS TABLE (Master Data)
-- ========================================
-- Purpose: Store hostel information
-- Relationships: Referenced by students (One-to-Many)

CREATE TABLE hostels (
    hostel_id INTEGER PRIMARY KEY AUTOINCREMENT,
    hostel_name VARCHAR(100) NOT NULL UNIQUE,
    hostel_type VARCHAR(20) NOT NULL CHECK (hostel_type IN ('BOYS', 'GIRLS', 'CO-ED')),
    address TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ========================================
-- 2. DEPARTMENTS TABLE (Master Data)
-- ========================================
-- Purpose: Store department information
-- Relationships: Referenced by students (One-to-Many)

CREATE TABLE departments (
    department_id INTEGER PRIMARY KEY AUTOINCREMENT,
    department_name VARCHAR(100) NOT NULL UNIQUE,
    department_code VARCHAR(10) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ========================================
-- 3. STUDENTS TABLE
-- ========================================
-- Purpose: Store student information
-- Relationships: 
--   - References hostels (Many-to-One)
--   - References departments (Many-to-One)
--   - Referenced by orders (One-to-Many)

CREATE TABLE students (
    student_id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    roll_number VARCHAR(20) NOT NULL UNIQUE,
    phone VARCHAR(15),
    password_hash VARCHAR(255) NOT NULL,
    hostel_id INTEGER REFERENCES hostels(hostel_id),
    department_id INTEGER REFERENCES departments(department_id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ========================================
-- 4. CANTEENS TABLE
-- ========================================
-- Purpose: Store canteen information
-- Relationships: Referenced by menu_items and orders (One-to-Many)

CREATE TABLE canteens (
    canteen_id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(100) NOT NULL,
    location VARCHAR(200),
    opening_time VARCHAR(10),
    closing_time VARCHAR(10),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ========================================
-- 5. MENU_ITEMS TABLE
-- ========================================
-- Purpose: Store food items available in canteens
-- Relationships:
--   - References canteens (Many-to-One)
--   - Referenced by order_items (One-to-Many)

CREATE TABLE menu_items (
    item_id INTEGER PRIMARY KEY AUTOINCREMENT,
    canteen_id INTEGER NOT NULL REFERENCES canteens(canteen_id),
    item_name VARCHAR(100) NOT NULL,
    description TEXT,
    price DECIMAL(10,2) NOT NULL CHECK (price > 0),
    category VARCHAR(50),
    is_vegetarian BOOLEAN DEFAULT TRUE,
    is_available BOOLEAN DEFAULT TRUE,
    image_url VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ========================================
-- 6. DELIVERY_PERSONNEL TABLE
-- ========================================
-- Purpose: Store delivery staff information
-- Relationships: Referenced by delivery_pickups (One-to-Many)

CREATE TABLE delivery_personnel (
    personnel_id INTEGER PRIMARY KEY AUTOINCREMENT,
    name VARCHAR(100) NOT NULL,
    phone VARCHAR(15) NOT NULL UNIQUE,
    is_available BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ========================================
-- 7. ORDERS TABLE (Transaction Header)
-- ========================================
-- Purpose: Store order header information
-- Relationships:
--   - References students (Many-to-One)
--   - References canteens (Many-to-One)
--   - Referenced by order_items (One-to-Many)
--   - Referenced by payments (One-to-One)
--   - Referenced by delivery_pickups (One-to-One)

CREATE TABLE orders (
    order_id INTEGER PRIMARY KEY AUTOINCREMENT,
    student_id INTEGER NOT NULL REFERENCES students(student_id),
    canteen_id INTEGER NOT NULL REFERENCES canteens(canteen_id),
    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    order_status VARCHAR(20) DEFAULT 'PLACED' 
        CHECK (order_status IN ('PLACED', 'PREPARING', 'READY', 'DELIVERED', 'CANCELLED')),
    order_type VARCHAR(20) NOT NULL CHECK (order_type IN ('PICKUP', 'DELIVERY')),
    total_amount DECIMAL(10,2) DEFAULT 0,
    special_instructions TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ========================================
-- 8. ORDER_ITEMS TABLE (Transaction Detail / Junction)
-- ========================================
-- Purpose: Store individual items in an order
-- Relationships:
--   - References orders (Many-to-One) with CASCADE delete
--   - References menu_items (Many-to-One)

CREATE TABLE order_items (
    order_item_id INTEGER PRIMARY KEY AUTOINCREMENT,
    order_id INTEGER NOT NULL REFERENCES orders(order_id) ON DELETE CASCADE,
    item_id INTEGER NOT NULL REFERENCES menu_items(item_id),
    quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0),
    unit_price DECIMAL(10,2) NOT NULL,
    subtotal DECIMAL(10,2) NOT NULL,
    notes TEXT
);

-- ========================================
-- 9. DELIVERY_PICKUPS TABLE
-- ========================================
-- Purpose: Store delivery/pickup details
-- Relationships:
--   - References orders (One-to-One) with CASCADE delete
--   - References delivery_personnel (Many-to-One)

CREATE TABLE delivery_pickups (
    delivery_id INTEGER PRIMARY KEY AUTOINCREMENT,
    order_id INTEGER NOT NULL UNIQUE REFERENCES orders(order_id) ON DELETE CASCADE,
    delivery_address TEXT,
    personnel_id INTEGER REFERENCES delivery_personnel(personnel_id),
    estimated_time VARCHAR(50),
    actual_delivery_time TIMESTAMP,
    is_delivered BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ========================================
-- 10. PAYMENTS TABLE
-- ========================================
-- Purpose: Store payment/billing information
-- Relationships:
--   - References orders (One-to-One) with CASCADE delete

CREATE TABLE payments (
    payment_id INTEGER PRIMARY KEY AUTOINCREMENT,
    order_id INTEGER NOT NULL UNIQUE REFERENCES orders(order_id) ON DELETE CASCADE,
    amount_paid DECIMAL(10,2) NOT NULL,
    payment_method VARCHAR(20) NOT NULL CHECK (payment_method IN ('CASH', 'UPI')),
    payment_status VARCHAR(20) DEFAULT 'PENDING' 
        CHECK (payment_status IN ('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED')),
    transaction_id VARCHAR(100),
    payment_date TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
"""

# ========================================
# DATA MANIPULATION (DML) - INSERT QUERIES
# ========================================

INSERT_QUERIES = """
-- ========================================
-- INSERT: Create a new student
-- ========================================
INSERT INTO students (name, email, roll_number, phone, password_hash, hostel_id, department_id)
VALUES ('Rahul Sharma', 'rahul@college.edu', 'CSE2024001', '9123456789', 
        'hashed_password_here', 1, 1);

-- ========================================
-- INSERT: Create a new menu item
-- ========================================
INSERT INTO menu_items (canteen_id, item_name, description, price, category, is_vegetarian)
VALUES (1, 'Masala Dosa', 'Crispy dosa with potato filling', 60.00, 'Breakfast', TRUE);

-- ========================================
-- INSERT: Place a new order (Transaction)
-- ========================================
BEGIN TRANSACTION;

-- Step 1: Create order header
INSERT INTO orders (student_id, canteen_id, order_type, order_status, special_instructions)
VALUES (1, 1, 'PICKUP', 'PLACED', 'Less spicy please');

-- Step 2: Get the new order_id
-- In most databases: SELECT LAST_INSERT_ID() or SELECT last_insert_rowid()

-- Step 3: Insert order items
INSERT INTO order_items (order_id, item_id, quantity, unit_price, subtotal)
VALUES 
    (1, 1, 2, 60.00, 120.00),  -- 2x Masala Dosa
    (1, 13, 1, 15.00, 15.00);  -- 1x Tea

-- Step 4: Update order total
UPDATE orders 
SET total_amount = (SELECT SUM(subtotal) FROM order_items WHERE order_id = 1)
WHERE order_id = 1;

COMMIT;
"""

# ========================================
# DATA MANIPULATION - SELECT QUERIES
# ========================================

SELECT_QUERIES = """
-- ========================================
-- SELECT: Get all students with hostel and department
-- Demonstrates: INNER JOIN / LEFT JOIN
-- ========================================
SELECT 
    s.student_id,
    s.name,
    s.email,
    s.roll_number,
    h.hostel_name,
    d.department_name,
    d.department_code
FROM students s
LEFT JOIN hostels h ON s.hostel_id = h.hostel_id
LEFT JOIN departments d ON s.department_id = d.department_id
ORDER BY s.name;

-- ========================================
-- SELECT: Get order history for a student
-- Demonstrates: JOIN, GROUP BY, aggregate functions
-- ========================================
SELECT 
    o.order_id,
    o.order_date,
    o.order_status,
    o.order_type,
    o.total_amount,
    GROUP_CONCAT(mi.item_name SEPARATOR ', ') as items,
    p.payment_status
FROM orders o
LEFT JOIN order_items oi ON o.order_id = oi.order_id
LEFT JOIN menu_items mi ON oi.item_id = mi.item_id
LEFT JOIN payments p ON o.order_id = p.order_id
WHERE o.student_id = 1
GROUP BY o.order_id
ORDER BY o.order_date DESC;

-- ========================================
-- SELECT: Get menu items with filters
-- Demonstrates: WHERE with multiple conditions
-- ========================================
SELECT 
    item_id,
    item_name,
    price,
    category,
    is_vegetarian,
    is_available
FROM menu_items
WHERE canteen_id = 1
  AND is_available = TRUE
  AND category = 'Breakfast'
ORDER BY item_name;

-- ========================================
-- SELECT: Get orders by status (for kitchen)
-- Demonstrates: Enum handling, JOIN
-- ========================================
SELECT 
    o.order_id,
    o.order_date,
    s.name as student_name,
    s.roll_number,
    o.order_type,
    o.special_instructions
FROM orders o
JOIN students s ON o.student_id = s.student_id
WHERE o.order_status = 'PLACED'
ORDER BY o.order_date ASC;

-- ========================================
-- SELECT: Get full order details
-- Demonstrates: Multiple JOINs
-- ========================================
SELECT 
    o.order_id,
    o.order_date,
    o.order_status,
    o.order_type,
    o.total_amount,
    s.name as student_name,
    s.roll_number,
    mi.item_name,
    oi.quantity,
    oi.unit_price,
    oi.subtotal,
    p.payment_method,
    p.payment_status,
    dp.delivery_address,
    dp.is_delivered,
    dperson.name as delivery_person
FROM orders o
JOIN students s ON o.student_id = s.student_id
LEFT JOIN order_items oi ON o.order_id = oi.order_id
LEFT JOIN menu_items mi ON oi.item_id = mi.item_id
LEFT JOIN payments p ON o.order_id = p.order_id
LEFT JOIN delivery_pickups dp ON o.order_id = dp.order_id
LEFT JOIN delivery_personnel dperson ON dp.personnel_id = dperson.personnel_id
WHERE o.order_id = 1;
"""

# ========================================
# AGGREGATE & REPORT QUERIES
# ========================================

REPORT_QUERIES = """
-- ========================================
-- REPORT: Daily Revenue
-- Demonstrates: Aggregate functions, GROUP BY, CASE WHEN
-- ========================================
SELECT 
    DATE(o.order_date) as date,
    COUNT(DISTINCT o.order_id) as total_orders,
    COUNT(DISTINCT CASE WHEN p.payment_status = 'COMPLETED' THEN o.order_id END) as completed_orders,
    COALESCE(SUM(CASE WHEN p.payment_status = 'COMPLETED' THEN p.amount_paid END), 0) as total_revenue,
    COALESCE(SUM(CASE WHEN p.payment_status = 'COMPLETED' AND p.payment_method = 'CASH' 
                 THEN p.amount_paid END), 0) as cash_revenue,
    COALESCE(SUM(CASE WHEN p.payment_status = 'COMPLETED' AND p.payment_method = 'UPI' 
                 THEN p.amount_paid END), 0) as upi_revenue
FROM orders o
LEFT JOIN payments p ON o.order_id = p.order_id
WHERE DATE(o.order_date) = '2024-01-10'
GROUP BY DATE(o.order_date);

-- ========================================
-- REPORT: Most Popular Items
-- Demonstrates: Subquery, ORDER BY with aggregate
-- ========================================
SELECT 
    mi.item_id,
    mi.item_name,
    mi.price,
    COUNT(oi.order_item_id) as times_ordered,
    SUM(oi.quantity) as total_quantity,
    SUM(oi.subtotal) as total_revenue
FROM menu_items mi
LEFT JOIN order_items oi ON mi.item_id = oi.item_id
GROUP BY mi.item_id
ORDER BY times_ordered DESC
LIMIT 10;

-- ========================================
-- REPORT: Student Order Summary
-- Demonstrates: Aggregate with GROUP BY
-- ========================================
SELECT 
    s.student_id,
    s.name,
    s.roll_number,
    COUNT(o.order_id) as total_orders,
    COALESCE(SUM(o.total_amount), 0) as total_spent
FROM students s
LEFT JOIN orders o ON s.student_id = o.student_id
GROUP BY s.student_id
ORDER BY total_spent DESC;

-- ========================================
-- REPORT: Category-wise Sales
-- Demonstrates: GROUP BY with JOIN
-- ========================================
SELECT 
    mi.category,
    COUNT(DISTINCT oi.order_item_id) as items_sold,
    SUM(oi.subtotal) as category_revenue
FROM menu_items mi
JOIN order_items oi ON mi.item_id = oi.item_id
GROUP BY mi.category
ORDER BY category_revenue DESC;
"""

# ========================================
# UPDATE QUERIES
# ========================================

UPDATE_QUERIES = """
-- ========================================
-- UPDATE: Change order status
-- Demonstrates: UPDATE with WHERE clause
-- ========================================
UPDATE orders 
SET order_status = 'PREPARING',
    updated_at = CURRENT_TIMESTAMP
WHERE order_id = 1;

-- ========================================
-- UPDATE: Toggle item availability
-- Demonstrates: UPDATE with NOT
-- ========================================
UPDATE menu_items
SET is_available = NOT is_available,
    updated_at = CURRENT_TIMESTAMP
WHERE item_id = 1;

-- ========================================
-- UPDATE: Complete payment
-- Demonstrates: UPDATE with multiple fields
-- ========================================
UPDATE payments
SET payment_status = 'COMPLETED',
    payment_date = CURRENT_TIMESTAMP,
    transaction_id = 'UPI123456789'
WHERE payment_id = 1;

-- ========================================
-- UPDATE: Confirm delivery
-- Demonstrates: UPDATE with datetime
-- ========================================
UPDATE delivery_pickups
SET is_delivered = TRUE,
    actual_delivery_time = CURRENT_TIMESTAMP
WHERE order_id = 1;
"""

# ========================================
# DELETE QUERIES
# ========================================

DELETE_QUERIES = """
-- ========================================
-- DELETE: Remove a menu item
-- Note: This will fail if there are order_items with this item_id
-- (Referential integrity constraint)
-- ========================================
DELETE FROM menu_items WHERE item_id = 5;

-- ========================================
-- DELETE: Cancel and remove an order
-- Due to CASCADE, this also deletes related:
--   - order_items
--   - payments  
--   - delivery_pickups
-- ========================================
DELETE FROM orders WHERE order_id = 3;
"""

# ========================================
# ADVANCED QUERIES (For VIVA)
# ========================================

ADVANCED_QUERIES = """
-- ========================================
-- SUBQUERY: Students who have never ordered
-- ========================================
SELECT s.student_id, s.name, s.email
FROM students s
WHERE s.student_id NOT IN (
    SELECT DISTINCT student_id FROM orders
);

-- ========================================
-- SUBQUERY: Items never ordered
-- ========================================
SELECT mi.item_id, mi.item_name
FROM menu_items mi
WHERE mi.item_id NOT IN (
    SELECT DISTINCT item_id FROM order_items
);

-- ========================================
-- HAVING: Departments with more than 2 students
-- ========================================
SELECT 
    d.department_code,
    d.department_name,
    COUNT(s.student_id) as student_count
FROM departments d
JOIN students s ON d.department_id = s.department_id
GROUP BY d.department_id
HAVING COUNT(s.student_id) > 2;

-- ========================================
-- SELF-JOIN: Find students in same hostel
-- ========================================
SELECT 
    s1.name as student1,
    s2.name as student2,
    h.hostel_name
FROM students s1
JOIN students s2 ON s1.hostel_id = s2.hostel_id AND s1.student_id < s2.student_id
JOIN hostels h ON s1.hostel_id = h.hostel_id;

-- ========================================
-- UNION: All orders (pickup and delivery) with type
-- ========================================
SELECT order_id, 'PICKUP' as type, NULL as delivery_address
FROM orders WHERE order_type = 'PICKUP'
UNION
SELECT o.order_id, 'DELIVERY' as type, dp.delivery_address
FROM orders o
JOIN delivery_pickups dp ON o.order_id = dp.order_id
WHERE o.order_type = 'DELIVERY';

-- ========================================
-- VIEW: Create a view for order summary
-- ========================================
CREATE VIEW order_summary AS
SELECT 
    o.order_id,
    s.name as student_name,
    o.order_date,
    o.order_status,
    o.total_amount,
    p.payment_status
FROM orders o
JOIN students s ON o.student_id = s.student_id
LEFT JOIN payments p ON o.order_id = p.order_id;

-- Usage:
SELECT * FROM order_summary WHERE order_status = 'PLACED';
"""

if __name__ == "__main__":
    print("="*60)
    print("COLLEGE CANTEEN FOOD ORDERING SYSTEM - SQL REFERENCE")
    print("="*60)
    print("\nThis file contains sample SQL queries for DBMS reference.")
    print("View this file in an editor to see all queries.\n")
    print("Sections included:")
    print("1. CREATE TABLE statements (DDL)")
    print("2. INSERT queries")
    print("3. SELECT queries with JOINs")
    print("4. Report queries with aggregates")
    print("5. UPDATE queries")
    print("6. DELETE queries")
    print("7. Advanced queries (subquery, having, union, view)")
